# This demonstrates exposing a WMS server as a HIPS service
# HIPS endpoints are:
# - http://localhost:8080/hips/mars_wms
# - http://localhost:8080/hips/mars_tiled_geodetic

services:
  demo:
  hips:
    #resampling_method: nearest_neighbour
    resampling_method: bilinear
    #resampling_method: bicubic
    # populate_cache: false
  #tms:
  #  use_grid_names: true
  #  # origin for /tiles service
  #  origin: 'nw'
  #kml:
  #    use_grid_names: true
  #wmts:
  #wms:
  #  srs: ['EPSG:4326', 'CRS:84', 'EPSG:32661']
  #  md:
  #    title: MapProxy WMS Proxy
  #    abstract: This is a minimal MapProxy example.

layers:
  - name: mars_wms
    title: MARS
    sources: [mars_wms]
    md:
        hips:
            # enabled: false
            creator_did: ivo://unknown.authority/mars_wms
            obs_title: MARS MOLA color
            foo: bar
            # hips_tile_width: 512
            # hips_order: 5

  - name: mars_tiled_geodetic
    title: MARS, using internal cache
    sources: [mars_tiled_geodetic]
    md:
        hips:
            creator_did: ivo://unknown.authority/mars_wms
            # obs_title: MARS MOLA color
            # foo: bar
            # hips_tile_width: 512
            # hips_order: 5


  # To illustrate HIPS passthrough mode
  - name: mars_hips_direct
    title: MARS
    sources: [mars_hips_source]
    md:
        hips:
            # Wen set to true (the default), all HIPS requests are directly
            # redirected to the HIPS source if the layer is a HIPS source.
            # Can be set to false to do HIPS -> geodetic -> HIPS, but much slower
            # passthrough: true

            # Wen set to true (the default), the /properties HIPS request is directly
            # redirected to the HIPS source if the layer is a HIPS source.
            # Can be set to false so that MapProxy create is own /properties response
            # passthrough_properties: true

caches:
  mars_tiled_geodetic:
    grids: [geodetic]
    sources: [mars_wms]


sources:
  mars_wms:
    type: wms
    req:
      url: https://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/mars/mars_simp_cyl.map&
      layers: MOLA_color

  # To illustrate HIPS passthrough mode
  mars_hips_source:
    type: hips
    image:
      format: image/jpeg
    resampling_method: bilinear
    url: http://alasky.u-strasbg.fr/Planets/Mars_MOLA
    # cache_hips_tiles: false

grids:
    geodetic:
        origin: nw
        base: GLOBAL_GEODETIC

globals:
