name: Running mapproxy-hips tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.12"]

    steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install proj-bin libgeos-dev libgdal-dev libxslt1-dev libxml2-dev build-essential libjpeg-dev zlib1g-dev libfreetype6-dev protobuf-compiler libprotoc-dev -y

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Use python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Cache python deps 💾
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.OS }}-python-${{ hashFiles('**/requirements-tests.txt') }}
        restore-keys: |
          ${{ runner.OS }}-python-
          ${{ runner.OS }}-

    - name: Install dependencies ⏬
      run: |
        pip install -r requirements.txt
        pip install pytest WebTest
        pip install -e .

    - name: Run tests 🏗️
      run: |
        export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:$LD_PRELOAD
        pytest mapproxy_hips
